[package]
name = "x-raffle-meta"
version = "0.0.0"
edition = "2018"
publish = false
authors = [ "you",]

[dev-dependencies]

[dependencies.x-raffle]
path = ".."

[dependencies.elrond-wasm-debug]
version = "0.36.1"
