// Code generated by the elrond-wasm multi-contract system. DO NOT EDIT.

////////////////////////////////////////////////////
////////////////// AUTO-GENERATED //////////////////
////////////////////////////////////////////////////

// Init:                                 1
// Endpoints:                           14
// Async Callback (empty):               1
// Total number of exported functions:  16

#![no_std]

elrond_wasm_node::wasm_endpoints! {
    xlauncher_presale
    (
        fundContract
        getTokenBalance
        buy
        collect
        setTokenInfo
        getCollectionIdentifier
        getNonce
        getTokenId
        getPrice
        getMinAmount
        getMaxAmount
        getMaxBalance
        getClientList
        getClientBoughtValue
    )
}

elrond_wasm_node::wasm_empty_callback! {}
